LAYOUTS = LAYOUT_split_3x6_3_ex2
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
RAW_ENABLE = yes
RGB_MATRIX_ENABLE = yes

# TEMP 
CONSOLE_ENABLE=yes

SRC += logic.c