RGBLIGHT_ENABLE = no

OLED_ENABLE = yes

LAYOUTS = LAYOUT_right_ball
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
# AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
# CAPS_WORD_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
RAW_ENABLE = yes
# RGB_MATRIX_ENABLE = yes
SRC += logic.c

# EXTRAFLAGS += -flto
# LTO_ENABLE = yes
# LINK_TIME_OPTIMIZATION_ENABLE = yes
LAYER_STATE_16BIT = yes

# TEMP 
CONSOLE_ENABLE=yes